### ISSUE TITLE
Include Setonix in HPC testing

### ISSUE THREAD

**Issue by angus-g** [g-adopt/g-adopt#174]
Either concurrent with Gadi, or separate?

**Comment by dsroberts** [comment]
Given its a `workflow_dispatch` task, you can add something like this:
```
    inputs:
        system:
          description: "Select a system to test on"
          required: false
          type: choice
          options:
            - gadi
            - setonix
```
Then a job that defines a `matrix` based on that choice, if the user doesn't make a choice, run on both.
